apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-credentials
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"

stringData:
  role_arn: "arn:aws:iam::{{ .Values.awsAccountId }}:role/{{ .Values.clusterName }}-RosaClusterWatchLogging"
---
apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "7"

spec:
  outputs:
    - name: cw
      type: cloudwatch
      cloudwatch:
        groupBy: namespaceName
        groupPrefix: rosa-{{ .Values.clusterName }}
        region: {{ .Values.awsRegion }}
      secret:
        name: cloudwatch-credentials
  pipelines:
     - name: to-cloudwatch
       inputRefs:
         - infrastructure
         - audit
         - application
       outputRefs:
         - cw
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  collection:
    logs:
       type: fluentd
  forwarder:
    fluentd: {}
  managementState: Managed

