kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-cluster-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: amazon-cloudwatch
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-dbaas-operator
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: ack-system
  - kind: ServiceAccount
    name: openshift-gitops-applicationset-controller
    namespace: openshift-gitops
  - kind: ServiceAccount
    name: openshift-gitops-argocd-server
    namespace: openshift-gitops
  - kind: ServiceAccount
    name: openshift-gitops-argocd-server
    namespace: openshift-cluster-csi-drivers
  - kind: ServiceAccount
    name: openshift-gitops-argocd-server
    namespace: mta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
