apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/kubecutle/rosa-idp.git
    targetRevision: HEAD
    path: efs
    directory:
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cluster-csi-drivers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - CreateNamespace=true
    - RespectIgnoreDifferences=true    
    retry:
      limit: 50
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
