apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rds-connections
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/open-sudo/rosa-idp.git
    targetRevision: HEAD
    path: gitlab-oauth
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-dbaas-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 50
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy


